using System.ComponentModel;

namespace persistent.enumeration
{
    public enum CoolingClassEnum
    {
        [Description("AA")]
        AA,
        [Description("AA/FA")]
        AAFA,
        [Description("AFA")]
        AFA,
        [Description("FOA")]
        FOA,
        [Description("FOW")]
        FOW,
        [Description("OA")]
        OA,
        [Description("OA/FA")]
        OAFA,
        [Description("OA/FA/FA")]
        OAFAFA,
        [Description("OA/FA/FOA")]
        OAFAFOA,
        [Description("OA/FOA/FOA")]
        OAFOAFOA,
        [Description("OW")]
        OW,
        [Description("OW/A")]
        OWA,
        [Description("ANV")]
        ANV,
        [Description("GA")]
        GA,
        [Description("Other")]
        Other,
        [Description("ONAF")]
        ONAF,
        [Description("ONAN")]
        ONAN,
        [Description("ONWN")]
        ONWN,
        [Description("ONWN/ONAN")]
        ONWNONAN,
        [Description("ONAN/ONAF")]
        ONANONAF,
        [Description("ONAN/ONAF/ONAF")]
        ONANONAFONAF,
        [Description("ONAN/ONAF/OFAF")]
        ONANONAFOFAF,
        [Description("ONAN/OFAF/ONAF")]
        ONANOFAFONAF,
        [Description("OFAF")]
        OFAF,
        [Description("OFWF")]
        OFWF,
        [Description("ODWF")]
        ODWF,
        [Description("ONAN/OFAN/OFAF")]
        ONANOFANOFAF,
        [Description("OFAN")]
        OFAN,
        [Description("OFAN/OFAF")]
        OFANOFAF,
        [Description("ONWF")]
        ONWF,
        [Description("AN")]
        AN,
        [Description("AF")]
        AF,
        [Description("ANAN")]
        ANAN,
        [Description("ANAF")]
        ANAF,
        [Description("GN")]
        GN,
        [Description("GF")]
        GF,
        [Description("GNAF")]
        GNAF,
        [Description("GNAN/GNAF")]
        GNANGNAF,
        [Description("GNAN")]
        GNAN,
    }
}
